#version: '3.9'

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: MyAdminUser
      MONGO_INITDB_ROOT_PASSWORD: MyAdminPassword
    networks:
      - my_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: MyAdminUser
      ME_CONFIG_MONGODB_ADMINPASSWORD: MyAdminPassword
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: MyAdminUser
      ME_CONFIG_BASICAUTH_PASSWORD: MyAdminPassword
      # Corrected URL to use MongoDB service name instead of localhost
      ME_CONFIG_MONGODB_URL: mongodb://MyAdminUser:MyAdminUser@mongodb:27017/admin
    depends_on:
      - mongodb
    networks:
      - my_network

volumes:
  data:

networks:
  my_network:
    driver: bridge